// ─── INDIA DATA ──────────────────────────────────────────────────────────────

export const INDIA_STATES = [
  { name: 'Andhra Pradesh',        capital: 'Amaravati' },
  { name: 'Arunachal Pradesh',     capital: 'Itanagar' },
  { name: 'Assam',                 capital: 'Dispur' },
  { name: 'Bihar',                 capital: 'Patna' },
  { name: 'Chhattisgarh',         capital: 'Raipur' },
  { name: 'Goa',                   capital: 'Panaji' },
  { name: 'Gujarat',               capital: 'Gandhinagar' },
  { name: 'Haryana',               capital: 'Chandigarh' },
  { name: 'Himachal Pradesh',      capital: 'Shimla' },
  { name: 'Jharkhand',             capital: 'Ranchi' },
  { name: 'Karnataka',             capital: 'Bengaluru' },
  { name: 'Kerala',                capital: 'Thiruvananthapuram' },
  { name: 'Madhya Pradesh',        capital: 'Bhopal' },
  { name: 'Maharashtra',           capital: 'Mumbai' },
  { name: 'Manipur',               capital: 'Imphal' },
  { name: 'Meghalaya',             capital: 'Shillong' },
  { name: 'Mizoram',               capital: 'Aizawl' },
  { name: 'Nagaland',              capital: 'Kohima' },
  { name: 'Odisha',                capital: 'Bhubaneswar' },
  { name: 'Punjab',                capital: 'Chandigarh' },
  { name: 'Rajasthan',             capital: 'Jaipur' },
  { name: 'Sikkim',                capital: 'Gangtok' },
  { name: 'Tamil Nadu',            capital: 'Chennai' },
  { name: 'Telangana',             capital: 'Hyderabad' },
  { name: 'Tripura',               capital: 'Agartala' },
  { name: 'Uttar Pradesh',         capital: 'Lucknow' },
  { name: 'Uttarakhand',           capital: 'Dehradun' },
  { name: 'West Bengal',           capital: 'Kolkata' },
  { name: 'Andaman & Nicobar',     capital: 'Port Blair' },
  { name: 'Chandigarh (UT)',        capital: 'Chandigarh' },
  { name: 'Dadra & Nagar Haveli',  capital: 'Daman' },
  { name: 'Delhi',                  capital: 'New Delhi' },
  { name: 'Jammu & Kashmir',       capital: 'Srinagar / Jammu' },
  { name: 'Ladakh',                 capital: 'Leh' },
  { name: 'Lakshadweep',            capital: 'Kavaratti' },
  { name: 'Puducherry',             capital: 'Puducherry' },
];

export const PUNJAB_DISTRICTS = [
  { name: 'Amritsar',                  hq: 'Amritsar' },
  { name: 'Barnala',                   hq: 'Barnala' },
  { name: 'Bathinda',                  hq: 'Bathinda' },
  { name: 'Faridkot',                  hq: 'Faridkot' },
  { name: 'Fatehgarh Sahib',           hq: 'Fatehgarh Sahib' },
  { name: 'Fazilka',                   hq: 'Fazilka' },
  { name: 'Ferozepur',                 hq: 'Ferozepur' },
  { name: 'Gurdaspur',                 hq: 'Gurdaspur' },
  { name: 'Hoshiarpur',                hq: 'Hoshiarpur' },
  { name: 'Jalandhar',                 hq: 'Jalandhar' },
  { name: 'Kapurthala',                hq: 'Kapurthala' },
  { name: 'Ludhiana',                  hq: 'Ludhiana' },
  { name: 'Malerkotla',                hq: 'Malerkotla' },
  { name: 'Mansa',                     hq: 'Mansa' },
  { name: 'Moga',                      hq: 'Moga' },
  { name: 'Mohali (SAS Nagar)',        hq: 'Mohali' },
  { name: 'Muktsar (Sri Muktsar Sahib)', hq: 'Muktsar' },
  { name: 'Pathankot',                 hq: 'Pathankot' },
  { name: 'Patiala',                   hq: 'Patiala' },
  { name: 'Rupnagar (Ropar)',          hq: 'Rupnagar' },
  { name: 'Sangrur',                   hq: 'Sangrur' },
  { name: 'Shaheed Bhagat Singh Nagar', hq: 'Nawanshahr' },
  { name: 'Tarn Taran',                hq: 'Tarn Taran' },
];

// State → Districts mapping for all states
export const STATE_DISTRICTS: Record<string, string[]> = {
  'Punjab': PUNJAB_DISTRICTS.map(d => d.name),
  'Haryana': ['Ambala','Bhiwani','Charkhi Dadri','Faridabad','Fatehabad','Gurugram','Hisar',
    'Jhajjar','Jind','Kaithal','Karnal','Kurukshetra','Mahendragarh','Nuh','Palwal','Panchkula',
    'Panipat','Rewari','Rohtak','Sirsa','Sonipat','Yamunanagar'],
  'Himachal Pradesh': ['Bilaspur','Chamba','Hamirpur','Kangra','Kinnaur','Kullu','Lahaul and Spiti',
    'Mandi','Shimla','Sirmaur','Solan','Una'],
  'Delhi': ['Central Delhi','East Delhi','New Delhi','North Delhi','North East Delhi','North West Delhi',
    'Shahdara','South Delhi','South East Delhi','South West Delhi','West Delhi'],
  'Rajasthan': ['Ajmer','Alwar','Banswara','Baran','Barmer','Bharatpur','Bhilwara','Bikaner',
    'Bundi','Chittorgarh','Churu','Dausa','Dholpur','Dungarpur','Ganganagar','Hanumangarh',
    'Jaipur','Jaisalmer','Jalore','Jhalawar','Jhunjhunu','Jodhpur','Karauli','Kota','Nagaur',
    'Pali','Pratapgarh','Rajsamand','Sawai Madhopur','Sikar','Sirohi','Tonk','Udaipur'],
  'Uttar Pradesh': ['Agra','Aligarh','Allahabad','Ambedkar Nagar','Amethi','Amroha','Auraiya',
    'Azamgarh','Baghpat','Bahraich','Ballia','Balrampur','Banda','Barabanki','Bareilly','Basti',
    'Bhadohi','Bijnor','Budaun','Bulandshahr','Chandauli','Chitrakoot','Deoria','Etah','Etawah',
    'Faizabad','Farrukhabad','Fatehpur','Firozabad','Gautam Buddha Nagar','Ghaziabad',
    'Ghazipur','Gonda','Gorakhpur','Hamirpur','Hapur','Hardoi','Hathras','Jalaun','Jaunpur',
    'Jhansi','Kannauj','Kanpur Dehat','Kanpur Nagar','Kasganj','Kaushambi','Kushinagar',
    'Lakhimpur Kheri','Lalitpur','Lucknow','Maharajganj','Mahoba','Mainpuri','Mathura','Mau',
    'Meerut','Mirzapur','Moradabad','Muzaffarnagar','Pilibhit','Pratapgarh','Raebareli',
    'Rampur','Saharanpur','Sambhal','Sant Kabir Nagar','Shahjahanpur','Shamli','Shrawasti',
    'Siddharthnagar','Sitapur','Sonbhadra','Sultanpur','Unnao','Varanasi'],
  'Maharashtra': ['Mumbai City','Mumbai Suburban','Thane','Pune','Nashik','Nagpur','Aurangabad',
    'Solapur','Kolhapur','Sangli','Satara','Raigad','Ratnagiri','Sindhudurg','Dhule','Nandurbar',
    'Jalgaon','Ahmednagar','Beed','Latur','Osmanabad','Nanded','Hingoli','Parbhani','Washim',
    'Akola','Amravati','Yavatmal','Wardha','Chandrapur','Gadchiroli','Gondia','Bhandara','Buldhana'],
  'Karnataka': ['Bangalore Urban','Bangalore Rural','Tumkur','Kolar','Chikkaballapura','Ramanagara',
    'Mandya','Mysore','Chamarajanagar','Hassan','Kodagu','Dakshina Kannada','Udupi',
    'Chikkamagaluru','Shivamogga','Davanagere','Chitradurga','Bellary','Raichur','Koppal',
    'Gadag','Dharwad','Haveri','Uttara Kannada','Belagavi','Vijayapura','Bagalkot',
    'Yadgir','Kalaburagi','Bidar'],
  'Tamil Nadu': ['Chennai','Coimbatore','Madurai','Tiruchirappalli','Salem','Tirunelveli',
    'Tiruppur','Vellore','Erode','Thoothukkudi','Dindigul','Thanjavur','Kancheepuram',
    'Villupuram','Cuddalore','Nagapattinam','Tiruvarur','Pudukkottai','Ramanathapuram',
    'Virudhunagar','Sivaganga','Ariyalur','Perambalur','Karur','Namakkal','Dharmapuri',
    'Krishnagiri','The Nilgiris','Tiruvannamalai','Ranipet','Tenkasi','Chengalpattu',
    'Kallakurichi','Mayiladuthurai'],
  'Gujarat': ['Ahmedabad','Surat','Vadodara','Rajkot','Bhavnagar','Jamnagar','Junagadh','Gandhinagar',
    'Anand','Mehsana','Kheda','Patan','Banaskantha','Sabarkantha','Aravalli','Mahisagar','Chhota Udaipur',
    'Dahod','Panchmahal','Vadodara Rural','Bharuch','Narmada','Tapi','Surat Rural','Navsari','Valsad','Dang'],
  'West Bengal': ['Kolkata','Howrah','Hooghly','North 24 Parganas','South 24 Parganas','Nadia',
    'Murshidabad','Bardhaman','Birbhum','Bankura','Purulia','West Midnapore','East Midnapore',
    'North Dinajpur','South Dinajpur','Malda','Jalpaiguri','Darjeeling','Alipurduar','Cooch Behar','Kalimpong'],
  'Madhya Pradesh': ['Bhopal','Indore','Gwalior','Jabalpur','Ujjain','Sagar','Rewa','Satna',
    'Ratlam','Dewas','Chhindwara','Vidisha','Shivpuri','Mandsaur','Neemuch','Rajgarh',
    'Sehore','Harda','Hoshangabad','Betul','Narsinghpur','Raisen','Katni','Damoh','Panna',
    'Chhatarpur','Tikamgarh','Datia','Guna','Ashoknagar','Sheopur','Morena','Bhind','Gwalior Rural'],
  'Kerala': ['Thiruvananthapuram','Kollam','Pathanamthitta','Alappuzha','Kottayam','Idukki',
    'Ernakulam','Thrissur','Palakkad','Malappuram','Kozhikode','Wayanad','Kannur','Kasaragod'],
  'Andhra Pradesh': ['Visakhapatnam','Vijayawada','Guntur','Nellore','Kurnool','Tirupati',
    'Kadapa','Rajahmundry','Kakinada','Eluru','Ongole','Anantapur','Chittoor','Srikakulam',
    'Vizianagaram','Krishna','West Godavari','East Godavari','Prakasam','Kurnool'],
  'Telangana': ['Hyderabad','Warangal','Nizamabad','Karimnagar','Khammam','Mahbubnagar',
    'Nalgonda','Adilabad','Medak','Rangareddy','Sangareddi','Siddipet','Vikarabad',
    'Suryapet','Yadadri Bhuvanagiri','Jangaon','Bhadradri Kothagudem','Mancherial'],
  'Jammu & Kashmir': ['Jammu','Srinagar','Anantnag','Baramulla','Budgam','Doda','Ganderbal',
    'Kathua','Kishtwar','Kulgam','Kupwara','Poonch','Pulwama','Rajouri','Ramban','Reasi',
    'Samba','Shopian','Udhampur'],
};

export const PROPERTY_TYPES = [
  { value: 'house',     label: 'House',     emoji: '🏠' },
  { value: 'villa',     label: 'Villa',     emoji: '🏡' },
  { value: 'apartment', label: 'Apartment', emoji: '🏢' },
  { value: 'plot',      label: 'Plot',      emoji: '📐' },
  { value: 'shop',      label: 'Shop',      emoji: '🏪' },
  { value: 'warehouse', label: 'Warehouse', emoji: '🏭' },
  { value: 'pg',        label: 'PG',        emoji: '🛏️' },
];

export const AMENITIES_LIST = [
  'Parking','Garden','CCTV','Power Backup','Gym','Pool',
  'Lift','Security','Wi-Fi','Generator','AC','Balcony',
  'Modular Kitchen','Terrace','Servant Room','Club House',
  'Children Play Area','Visitor Parking','Gas Pipeline','Solar Power',
  'Vastu',
];

export const LISTING_COLORS: Record<string, string> = {
  sale: '#1e3a8a',
  rent: '#0f766e',
};

export const TYPE_EMOJI: Record<string, string> = {
  house: '🏠', villa: '🏡', apartment: '🏢',
  plot: '📐', shop: '🏪', warehouse: '🏭', pg: '🛏️',
};
